### ISSUE TITLE
Kanban Board : HandyMate

### ISSUE THREAD

**Issue by yetemegn-telaye** [PrantoshB/HandyMate-Backend#16]
[Here is a link for the board](https://github.com/users/PrantoshB/projects/11)

Note: There are 5 members in our team
 - @utsargo 
 - @yetemegn-telaye 
 - @PrantoshB 
 - @JacintaNgwu 
 - @haliljon 

**Initial Screenshot**

![screencapture-github-users-PrantoshB-projects-11-views-1-2023-05-17-20_00_29](https://github.com/PrantoshB/HandyMate-Backend/assets/6623974/a2ed06f6-9726-4986-8cd5-add65c82d7d2)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)
- [OPTIONAL] Ensure that you are adding realistic weight to your tasks.

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Thanks @mcrd25 for the suggestions 🙇🏽‍♂️❤️

We'll consider implementing those 💪🏼
